# Generated by Django 4.1.4 on 2022-12-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
    ]
